### ISSUE TITLE
6.3 jena_climate target leakage problem

### ISSUE THREAD

**Issue by Dolores2333** [fchollet/deep-learning-with-python-notebooks#136]
The author foget deleting the temperature column in the float_data which is used as a pool for sampling. Thus the outcome looks perfect due to the target leakage. 

Delete the target response when try the code yourself, though it will let u see how bad the Network performs. 😄 

`temp = float_data[:, 1]
a = float_data[:, 0]
a = np.reshape(a, newshape=(len(a), 1))
b = float_data[:, 2:]
print(a.shape, b.shape)
float_data = np.concatenate([a, b], axis=1)`

**Comment by zaquest** [comment]
The objective is to predict *future* temperature values, while doing so it is perfectly fine to use past values of the target variable. In fact there are methods that rely solely on the target variable history to predict future values (e.g. the naive method author used as a baseline).

**Comment by Dolores2333** [comment]
I see. Thanks for your rely!
