### ISSUE TITLE
Unclear how to download data used in 6.3

### ISSUE THREAD

**Issue by dansbecker** [fchollet/deep-learning-with-python-notebooks#4]
The instructions in 6.3 say the data is 

> recorded at the Weather Station at the Max-Planck-Institute for Biogeochemistry in Jena, Germany: http://www.bgc-jena.mpg.de/wetter/.

The data file name in the code is `jena_climate_2009_2016.csv`.  The website allows us to download data in 6-month increments, so the period 2009-2016 is split into 16 files.

Were these files concatenated to form the file used in the notebook?  If so, a sentence to that effect might clarify where the data came from. Alternatively, if `jena_climate_2009_2016.csv` isn't the concatenation of these files, I think it's unclear where a reader would find the data.

**Comment by fchollet** [comment]
You can download it at: https://s3.amazonaws.com/keras-datasets/jena_climate_2009_2016.csv.zip

**Comment by fchollet** [comment]
(this is explained in the book, but I guess I didn't include it in the notebook)

**Comment by agilebean** [comment]
@fchollet Could you update the 6.3 jupyter notebook with the link you gave above? I guess for other users it takes time to find this link, as it currently says:
```
data_dir = '/home/ubuntu/data/'
fname = os.path.join(data_dir, 'jena_climate_2009_2016.csv')
```
