### ISSUE TITLE
Listing 6.37. Training and evaluating a densely connected model - stalls on first epoch

### ISSUE THREAD

**Issue by jswift24** [fchollet/deep-learning-with-python-notebooks#49]
Having trouble getting listing 6.37 to work. The model stalls on the first epoch. Getting the following output, but it never reaches the end of epoch 1:

```
Epoch 1/20
496/500 [============================>.] - ETA: 0s - loss: 1.2985
```
Prior code in this chapter and code in prior chapters works fine. Any suggestions?

Thanks,

**Comment by driesbuyck** [comment]
In the book, listing 6.34 has an error. The last 2 steps need // batch_size.
So 

val_steps = (300000 - 200001 - lookback)//batch_size
test_steps = (len(float_data) - 300001 - lookback)//batch_si

**Comment by jswift24** [comment]
Thanks. That works.
