### ISSUE TITLE
6.3:  AttributeError: module 'numpy.random' has no attribute 'randit'

### ISSUE THREAD

**Issue by combstraight** [fchollet/deep-learning-with-python-notebooks#99]
Hello,

I am currently getting the error: `AttributeError: module 'numpy.random' has no attribute 'randit'` when running `model.fit_generator()`.   However, the `numpy.random.randit()` works fine when we call `generator()` directly.  

I have run `pip3 install numpy` as well as `python3 -m pip install numpy` to make sure numpy is update.  

I am currently running a jupyter notebook on a Ubuntu 16.04 machine.

**Comment by combstraight** [comment]
I have solved the problem by simply copy and pasting the exact code from the Jupyter notebook hosted on the github instead of manually writing it out on my notebook.   Still a curious error.   I will keep this issue open for 24 hours to invite any best guesses for the error.

**Comment by shukkkur** [comment]
@combstraight bro you misspelled randi**N**t 
```
np.random.randint
```

**Comment by ifond** [comment]
​ I have received your E-mail——Steven Lee
